# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: menv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - conda-tree
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - pip
