name: bw
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core funcitonality
  - python=3.10
  # dependency management
  - conda-tree
  # data science
  - jupyterlab
  - scipy  
  - pandas
  - numpy
  - openpyxl
  # plotting
  - matplotlib
  # lca
  - brightway2
  # pip packages
  - pip
